# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-states-teracloud-laas-prod-us-west-2"
    dynamodb_table = "terraform-locks-teracloud-laas-prod"
    encrypt        = true
    key            = "laas/terraform.tfstate"
    region         = "us-west-2"
  }
}
