# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-states-teracloud-laas-dev-us-west-2"
    dynamodb_table = "terraform-locks-teracloud-laas-dev"
    encrypt        = true
    key            = "laas/s3_input.tfstate"
    region         = "us-west-2"
  }
}
